version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: eltonsantana/reverseproxy
  udagram-users-api:
    build:
      context: ../../udagram-apis/udagram-users-api/
    image: eltonsantana/udagram-users-api
  udagram-feed-api:
    build:
      context: ../../udagram-apis/udagram-feed-api/
    image: eltonsantana/udagram-feed-api
  udagram-frontend:
    build:
      context: ../../udagram-frontend/
    image: eltonsantana/udagram-frontend