language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build udagram-apis/udagram-feed-api/. -t udagram-feed-api
  - docker build udagram-apis/udagram-users-api/. -t udagram-users-api
  - docker build udagram-frontend/. -t udagram-frontend
  - docker tag udagram-feed-api eltonsantana/udagram-feed-api:latest
  - docker tag udagram-users-api eltonsantana/udagram-users-api:latest
  - docker tag udagram-frontend eltonsantana/udagram-frontend:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push eltonsantana/udagram-feed-api
  - docker push eltonsantana/udagram-users-api
  - docker push eltonsantana/udagram-frontend